[tool.poetry]
name = "hackernews_developers"
version = "0.1.0"
description = "List of HackerNews Developers"
authors = ["Rasul Kireev <me@rasulkireev.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django-allauth = "^0.50.0"
python-webpack-boilerplate = "^1.0.0"
django-widget-tweaks = "^1.4.12"
django-environ = "^0.10.0"
psycopg2 = "^2.9.5"
django-model-utils = "^4.3.1"
django-q = "^1.3.9"
croniter = "^1.3.8"
httpx = "^0.23.3"
openai = "^0.27.2"
django-autoslug = "^1.9.8"
markdown = "^3.4.1"
gunicorn = "^20.1.0"
pillow = "^9.4.0"
django-extensions = "^3.2.1"
django-filter = "^22.1"
django-anymail = {extras = ["mailgun"], version = "^9.1"}
pygments = "^2.14.0"
dj-stripe = "^2.7.3"
whitenoise = "^6.4.0"
django = "^4.1.7"
wagtail = "^5.0"
django-taggit = "^3.1.0"
django-modelcluster = "^6.0"
libgravatar = "^1.0.4"
django-storages = "^1.13.2"
boto3 = "^1.26.137"
sentry-sdk = "^1.23.1"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
kolo = "^2.6.0"
jupyterlab = "^3.6.3"
pandas = "^2.0.1"
pylint = "^2.17.4"
pylint-django = "^2.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 120
multi_line_output = 3

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'

[tool.djlint]
profile="django"
ignore = "H031"

[tool.ruff]
line-length = 120
